#!/bin/bash

# Install github CLI (workaround instead of `apt install`
# requires ~/.config/gh/hosts.yml like this: 
#github.com:
#    user: scottyhq
#    oauth_token: xxxxxxxxxxxxxxxxxxxxxx
wget https://github.com/cli/cli/releases/download/v0.11.0/gh_0.11.0_linux_amd64.deb
dpkg -x gh_0.11.0_linux_amd64.deb /srv/conda/gh
ln -s /srv/conda/gh/usr/local/bin/gh /srv/conda/bin/gh

# Install packages that are not availble on conda-forge
# (/srv/conda/envs/notebook/bin/R)
R --save -e 'library("devtools"); 
             install.packages("precommit", repos="http://cran.us.r-project.org");
             install.packages("descr", repos="http://cran.us.r-project.org");
             '

# switch to installing development version in DSSG-eiCompare org
#             install_github("lorenc5/eiCompare")'

# Installing from private repository requires personal access token
#             install_github("DSSG-eiCompare/eiCompare")
#https://stackoverflow.com/questions/21171142/how-to-install-r-package-from-private-repo-using-devtools-install-github

#EOF
